### ISSUE TITLE
hdpath String is not yet implemented ? 

### ISSUE THREAD

**Issue by TOMOAKI12345** [ConsenSys/eth-lightwallet#104]
### when going to generate index 1 address (1st address)
```
var lightwallet = require("eth-lightwallet");
var keythereum = require("keythereum");
var secretSeed = "police club trick jealous together tunnel clarify sustain enforce vast absurd matrix";
var password = "test";
var _getPrivAddressByIndex = function(indexNum) {
    if(indexNum <= 0) throw Error("address index should be starting from 1")
    lightwallet.keystore.deriveKeyFromPassword(password, function (err, pwDerivedKey) {
        console.time();
        var ks = new lightwallet.keystore(secretSeed, pwDerivedKey);
        // lightwallet module doesn't have the method to get the given index address and secret
        // ex) if indexNum is 1003, hdPathString is "m/0'/0'/1'"
        // And the generate is 3
        // 1- 999 is "m/0'/0'/0'"
        // 1000- 1999 is "m/0'/1'/0'"
        // 2000 -2999 is "m/0'/2'/0'"
        var hdPathString = "m/0'/" + (indexNum - indexNum % 1000) / 1000  + "'/" + 0 + "'"
        var generateAddressNum = (indexNum % 1000 == 0)? 1: indexNum % 1000;
        console.log("hdpath " + hdPathString)
        console.log("number of addresses to generate " +  generateAddressNum)
        ks.generateNewAddress(pwDerivedKey, generateAddressNum, hdPathString);
        var addresses = ks.getAddresses();
        var address = addresses[generateAddressNum - 1];
        var exportedPriv = ks.exportPrivateKey(address, pwDerivedKey)
        console.log("generated address and private key is " + JSON.stringify([address, exportedPriv]));
        return [address, exportedPriv]
    });
}
var addressAndPriv = _getPrivAddressByIndex(1);
```
### Then the result is 
```
$ node exampleEtherGenerateAddress.js 
hdpath m/0'/0'/0'
number of addresses to generate 1
{ 'm/0\'/0\'/0\'': 
   { info: { curve: 'secp256k1', purpose: 'sign' },
     encHdPathPriv: 
      { encStr: 'Qp3li7Cr6eFI8dybiziRX7/56R/EnKUZVgwh2022/caO4HXO5efSFaLGHXmQacAWVdowxerOYrME5ZHU870+MZ39/447YfkDIfI2UnwCf/dKRNQc8Rijvsp0y4cJBulhcbyWef/rDAUBcZON79BOR8ddMQ/szqhxhr1DFjK4Bw==',
        nonce: 'dpuxp5OVtokxIYCzsLdSJfFBCusnnvcN' },
     hdIndex: 0,
     encPrivKeys: {},
     addresses: [] } }
generated address and private key is ["14adb0788d887ec5d5bb71a7d37a8389a896558f","74b081765d2546a3831f0d4c23a20986cd2e6a6381479fe156dc32287dc5117b"]
```

### and when going to generate 999th 
```
var lightwallet = require("eth-lightwallet");
var keythereum = require("keythereum");
var secretSeed = "police club trick jealous together tunnel clarify sustain enforce vast absurd matrix";
var password = "test";
var _getPrivAddressByIndex = function(indexNum) {
    if(indexNum <= 0) throw Error("address index should be starting from 1")
    lightwallet.keystore.deriveKeyFromPassword(password, function (err, pwDerivedKey) {
        console.time();
        var ks = new lightwallet.keystore(secretSeed, pwDerivedKey);
        // lightwallet module doesn't have the method to get the given index address and secret
        // ex) if indexNum is 1003, hdPathString is "m/0'/0'/1'"
        // And the generate is 3
        // 1- 999 is "m/0'/0'/0'"
        // 1000- 1999 is "m/0'/1'/0'"
        // 2000 -2999 is "m/0'/2'/0'"
        var hdPathString = "m/0'/" + (indexNum - indexNum % 1000) / 1000  + "'/" + 0 + "'"
        var generateAddressNum = (indexNum % 1000 == 0)? 1: indexNum % 1000;
        console.log("hdpath " + hdPathString)
        console.log("number of addresses to generate " +  generateAddressNum)
        ks.generateNewAddress(pwDerivedKey, generateAddressNum, hdPathString);
        var addresses = ks.getAddresses();
        var address = addresses[generateAddressNum - 1];
        var exportedPriv = ks.exportPrivateKey(address, pwDerivedKey)
        console.log("generated address and private key is " + JSON.stringify([address, exportedPriv]));
        return [address, exportedPriv]
    });
}
var addressAndPriv = _getPrivAddressByIndex(999);
```

### then the result is
``` 
$ node exampleEtherGenerateAddress.js 
hdpath m/0'/0'/0'
number of addresses to generate 999
{ 'm/0\'/0\'/0\'': 
   { info: { curve: 'secp256k1', purpose: 'sign' },
     encHdPathPriv: 
      { encStr: 'I2BD7emNYC9n8d5Uvw4ruGEfLY7Xdtn58tlnBbgRVdB09Uw4ttOnjx+atzX5QfnQb8nEn1v40iJIWLRXwuFQnghFh27AJuPxuVD/CBMqNNOm0Ukv3xcOey8g7XG5uwwXtd3XUQuDmBcvRFa22wDSo4kH0kRDw4ocfPqDU5xjYA==',
        nonce: 'R7rQ1hd0JjfJwfFHpfugrC/x+HvvDQq5' },
     hdIndex: 0,
     encPrivKeys: {},
     addresses: [] } }
generated address and private key is ["aa07af9bf584e64e355bd51101cb8f8e0e9bfc4b","9365b6dd26e705c9d6123c1f2790910bfbf21e3a033efe8dba2deb4938ee7cdf"]
```

### but when 2001th 
```
var lightwallet = require("eth-lightwallet");
var keythereum = require("keythereum");
var secretSeed = "police club trick jealous together tunnel clarify sustain enforce vast absurd matrix";
var password = "test";
var _getPrivAddressByIndex = function(indexNum) {
    if(indexNum <= 0) throw Error("address index should be starting from 1")
    lightwallet.keystore.deriveKeyFromPassword(password, function (err, pwDerivedKey) {
        console.time();
        var ks = new lightwallet.keystore(secretSeed, pwDerivedKey);
        // lightwallet module doesn't have the method to get the given index address and secret
        // ex) if indexNum is 1003, hdPathString is "m/0'/0'/1'"
        // And the generate is 3
        // 1- 999 is "m/0'/0'/0'"
        // 1000- 1999 is "m/0'/1'/0'"
        // 2000 -2999 is "m/0'/2'/0'"
        var hdPathString = "m/0'/" + (indexNum - indexNum % 1000) / 1000  + "'/" + 0 + "'"
        var generateAddressNum = (indexNum % 1000 == 0)? 1: indexNum % 1000;
        console.log("hdpath " + hdPathString)
        console.log("number of addresses to generate " +  generateAddressNum)
        ks.generateNewAddress(pwDerivedKey, generateAddressNum, hdPathString);
        var addresses = ks.getAddresses();
        var address = addresses[generateAddressNum - 1];
        var exportedPriv = ks.exportPrivateKey(address, pwDerivedKey)
        console.log("generated address and private key is " + JSON.stringify([address, exportedPriv]));
        return [address, exportedPriv]
    });
}
var addressAndPriv = _getPrivAddressByIndex(2011);
```
### Then it fails
```
$ node testGenerateAddress.js 
hdpath m/0'/2'/0'
number of addresses to generate 11
hdpath m/0'/2'/0'
number of addresses to generate 11
/Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/node_modules/eth-lightwallet/lib/keystore.js:135
  var secretbox = nacl.util.decodeBase64(encryptedStr.encStr);
                                                     ^

TypeError: Cannot read property 'encStr' of undefined
    at Function.KeyStore._decryptString (/Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/node_modules/eth-lightwallet/lib/keystore.js:135:54)
    at KeyStore.isDerivedKeyCorrect (/Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/node_modules/eth-lightwallet/lib/keystore.js:115:29)
    at KeyStore.generateNewAddress (/Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/node_modules/eth-lightwallet/lib/keystore.js:444:12)
    at /Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/exampleEtherGenerateAddress.js:20:12
    at cb (/Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/node_modules/eth-lightwallet/lib/keystore.js:531:7)
    at /Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/node_modules/scrypt-async/scrypt-async.js:474:9
    at Immediate._onImmediate (/Users/tom/Documents/workspace_js/AsianPayPoloniexEtherwallet/node_modules/scrypt-async/scrypt-async.js:433:11)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by christianlundkvist** [comment]
Hi @TOMOAKI12345! There is a mistake in the README, the function getAddress() requires that you pass in the hdPathString in order to get the addresses associated with that hdPathString.

**Comment by TOMOAKI12345** [comment]
@christianlundkvist   I have changed these to 
        var ks = new lightwallet.keystore(secretSeed, pwDerivedKey, hdPathString);
        var addresses = ks.getAddresses(hdPathString);

and change my index mistake 
    to   
        var generateAddressNum = indexNum % 1000 + 1;

### When going to generate index 2011 address ("m/0'/2'/0'" 12th address)
```
var lightwallet = require("eth-lightwallet");
var keythereum = require("keythereum");
var secretSeed = "police club trick jealous together tunnel clarify sustain enforce vast absurd matrix";
var password = "test";
var _getPrivAddressByIndex = function(indexNum) {
    if(indexNum <= 0) throw Error("address index should be starting from 1")
    lightwallet.keystore.deriveKeyFromPassword(password, function (err, pwDerivedKey) {
        console.time();
        var hdPathString = "m/0'/" + (indexNum - indexNum % 1000) / 1000  + "'/" + 0 + "'"
        var ks = new lightwallet.keystore(secretSeed, pwDerivedKey, hdPathString);
        // lightwallet module doesn't have the method to get the given index address and secret
        // ex) if indexNum is 1003, hdPathString is "m/0'/0'/1'"
        // And the generate is 3
        // 1- 999 is "m/0'/0'/0'"
        // 1000- 1999 is "m/0'/1'/0'"
        // 2000 -2999 is "m/0'/2'/0'"
        var generateAddressNum = indexNum % 1000 + 1;
        console.log("hdpath " + hdPathString)
        console.log("number of addresses to generate " +  generateAddressNum)
        ks.generateNewAddress(pwDerivedKey, generateAddressNum, hdPathString);
        var addresses = ks.getAddresses(hdPathString);
        var address = addresses[generateAddressNum - 1];
        var exportedPriv = ks.exportPrivateKey(address, pwDerivedKey)
        console.log("generated address and private key is " + JSON.stringify([address, exportedPriv]));
        return [address, exportedPriv]
    });
}
var addressAndPriv = _getPrivAddressByIndex(2011);
```

### then the result is 
```
$ node exampleEtherGenerateAddress
hdpath m/0'/2'/0'
number of addresses to generate 12
{ 'm/0\'/2\'/0\'': 
   { info: { curve: 'secp256k1', purpose: 'sign' },
     encHdPathPriv: 
      { encStr: 'BmBF+06V5xIuHeaU8rUnw9QlMFsTMujgmNy1fiptZALCfYmiLyP25faPQ52OleQDdIDy0ETxFlMR9JVyNS7hW8T7hj8kk3F6Ym9pdovR/MyOsOkeur1rYpZHJ07v8kFxi/SpFRDTIA9oFdarrmtaBlXWfL/2u60IllhwqcRZ/g==',
        nonce: 'ZN/D2BCvI+A1JmMGvUoVeESYWmCDFAEo' },
     hdIndex: 0,
     encPrivKeys: {},
     addresses: [] } }
                                    police club trick jealous together tunnel clarify sustain enforce vast absurd matrix
generated address and private key is ["878f75528888854da98e6ac96dd5630c6786c3c4","e2e6ec40050de8489b56dc2bce0a55d78e62ced9212395a25ca29cc1e9b26f0c"]

```

### works ! thanks  : )
