### ISSUE TITLE
TypeError: undefined is not a function from lightwallet.keystore.deriveKeyFromPassword()

### ISSUE THREAD

**Issue by tymat** [ConsenSys/eth-lightwallet#58]
Getting the following error in lightwallet.keystore.deriveKeyFromPassword in nodejs

**Version**
```
    "eth-lightwallet": "^2.2.0",
```

**Error**
```
> TypeError: undefined is not a function
    at new KeyStore (/Users/aeufemio/projects/digixglobal/web/accountmanager/node_modules/eth-lightwallet/lib/keystore.js:80:27)
    at cb (/Users/aeufemio/projects/digixglobal/web/accountmanager/node_modules/eth-lightwallet/lib/keystore.js:433:5)
    at /Users/aeufemio/projects/digixglobal/web/accountmanager/node_modules/eth-lightwallet/node_modules/scrypt-async/scrypt-async.js:474:9
    at Immediate._onImmediate (/Users/aeufemio/projects/digixglobal/web/accountmanager/node_modules/eth-lightwallet/node_modules/scrypt-async/scrypt-async.js:433:11)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by christianlundkvist** [comment]
@tymat Looks like this is the offending line:
```js
    var paddedSeed = (' '.repeat(120) + mnemonic).slice(-120);
```
So it looks like it doesn't recognize the `repeat` function. This function might be relatively new, what version of node are you using?

**Comment by tymat** [comment]
Forgot to add node version info:

```
$ node --version
v0.12.10
```

**Comment by tymat** [comment]
Will try on 5.6.0 now.

**Comment by christianlundkvist** [comment]
@tymat Any luck with this?

**Comment by tymat** [comment]
Yes. `nodejs-5.6.0` works just fine.

**Comment by Vijay-clustrex** [comment]
@tymat  Getting this same issue, my node version is 6.9.2 , Getting "lightwallet.keystore.deriveKeyFromPassword is not an function" . Any suggestions please

**Comment by Hunter-Nomad** [comment]
I have this problem too
"lightwallet.keystore.deriveKeyFromPassword is not an function"

```
lightwallet.keystore.deriveKeyFromPassword('12321',
    function (err, pwDerivedKey) {
        var seed = lightwallet.keystore.generateRandomSeed();
        var keystore = new lightwallet.keystore(seed, pwDerivedKey);

        keystore.generateNewAddress(pwDerivedKey);
        var address = keystore.getAddresses()[0];
        var prv_key = keystore.exportPrivateKey(address, pwDerivedKey);
        console.log('address and key: ', address, prv_key);
});
```

**Comment by sriharikapu** [comment]
![screen shot 2018-11-30 at 2 39 20 pm](https://user-images.githubusercontent.com/6247133/49272814-d1223680-f4ad-11e8-8fa8-99173cdb9b4a.png)
